import type { Locale } from './locale'

interface Feedback { storage: string; copy: string; input: string; retry: string; account: string; blog: string; continueUnsaved: string }
export const FEEDBACK: Record<Locale, Feedback> = {
  en: { storage: 'Your browser could not save this draft. Copy it before signing in or leaving this page.', copy: 'Could not copy. Check your browser clipboard permission and try again.', input: 'Check the context and complete every question. Option names must be unique.', retry: 'Retry', account: 'The account request failed. Please try again.', blog: 'Blog', continueUnsaved: 'Continue without saving' },
  'zh-CN': { storage: '浏览器无法保存草稿，请在登录或离开页面前复制内容。', copy: '复制失败，请检查浏览器剪贴板权限后重试。', input: '请检查上下文并填完整每个问题，选项名称不能重复。', retry: '重试', account: '账号操作失败，请重试。', blog: '博客（英文）', continueUnsaved: '不保存草稿，继续登录' },
  es: { storage: 'El navegador no pudo guardar el borrador. Cópialo antes de iniciar sesión o salir.', copy: 'No se pudo copiar. Revisa el permiso del portapapeles e inténtalo de nuevo.', input: 'Revisa el contexto y completa todas las preguntas. Los nombres de las opciones deben ser únicos.', retry: 'Reintentar', account: 'La operación de cuenta falló. Inténtalo de nuevo.', blog: 'Blog (en inglés)', continueUnsaved: 'Continuar sin guardar' },
  ja: { storage: '下書きを保存できませんでした。ログインやページ移動の前にコピーしてください。', copy: 'コピーできませんでした。クリップボードの権限を確認して再試行してください。', input: 'コンテキストを確認し、すべての質問を完成させてください。選択肢名は重複できません。', retry: '再試行', account: 'アカウント操作に失敗しました。再試行してください。', blog: 'ブログ（英語）', continueUnsaved: '保存せずに続行' },
  ko: { storage: '초안을 저장하지 못했습니다. 로그인하거나 페이지를 떠나기 전에 복사해 주세요.', copy: '복사하지 못했습니다. 클립보드 권한을 확인하고 다시 시도해 주세요.', input: '맥락을 확인하고 모든 질문을 완성해 주세요. 선택지 이름은 중복될 수 없습니다.', retry: '다시 시도', account: '계정 작업에 실패했습니다. 다시 시도해 주세요.', blog: '블로그 (영어)', continueUnsaved: '저장하지 않고 계속' },
  fr: { storage: 'Le navigateur n’a pas pu enregistrer le brouillon. Copiez-le avant de vous connecter ou de quitter la page.', copy: 'La copie a échoué. Vérifiez l’autorisation du presse-papiers et réessayez.', input: 'Vérifiez le contexte et complétez chaque question. Les noms des options doivent être uniques.', retry: 'Réessayer', account: 'L’opération a échoué. Veuillez réessayer.', blog: 'Blog (en anglais)', continueUnsaved: 'Continuer sans enregistrer' },
  de: { storage: 'Der Entwurf konnte nicht gespeichert werden. Kopieren Sie ihn vor der Anmeldung oder dem Verlassen der Seite.', copy: 'Kopieren fehlgeschlagen. Prüfen Sie die Berechtigung für die Zwischenablage und versuchen Sie es erneut.', input: 'Prüfen Sie den Kontext und vervollständigen Sie alle Fragen. Optionsnamen müssen eindeutig sein.', retry: 'Erneut versuchen', account: 'Die Kontoaktion ist fehlgeschlagen. Bitte versuchen Sie es erneut.', blog: 'Blog (Englisch)', continueUnsaved: 'Ohne Speichern fortfahren' },
  'pt-BR': { storage: 'O navegador não conseguiu salvar o rascunho. Copie-o antes de entrar ou sair da página.', copy: 'Não foi possível copiar. Verifique a permissão da área de transferência e tente novamente.', input: 'Confira o contexto e preencha todas as perguntas. Os nomes das opções devem ser únicos.', retry: 'Tentar novamente', account: 'A operação da conta falhou. Tente novamente.', blog: 'Blog (em inglês)', continueUnsaved: 'Continuar sem salvar' },
}
